workflows:
  build-android:
    name: Build Android
    max_build_duration: 30
    environment:
      vars:
        ANDROID_KEYSTORE_PASSWORD: $ANDROID_KEYSTORE_PASSWORD
        ANDROID_KEY_PASSWORD: $ANDROID_KEY_PASSWORD
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          flutter pub cache repair
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
